(defun taz_s_section_cbeam_draw_parametres_upe ()

;; UPE 80
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "80"))
    (progn
      (setq taz_s_h 80.0)
      (setq taz_s_b 50.0)
      (setq taz_s_tw 4.0)
      (setq taz_s_tf 7.0)
      (setq taz_s_r1 10.0)
      (setq taz_s_ey 18.2)
      (setq taz_s_section_area 10.10)
    )
  )
;; UPE 100
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "100"))
    (progn
      (setq taz_s_h 100.0)
      (setq taz_s_b 55.0)
      (setq taz_s_tw 4.5)
      (setq taz_s_tf 7.5)
      (setq taz_s_r1 10.0)
      (setq taz_s_ey 19.1)
      (setq taz_s_section_area 12.50)
    )
  )
;; UPE 120
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "120"))
    (progn
      (setq taz_s_h 120.0)
      (setq taz_s_b 60.0)
      (setq taz_s_tw 5.0)
      (setq taz_s_tf 8.0)
      (setq taz_s_r1 12.0)
      (setq taz_s_ey 19.8)
      (setq taz_s_section_area 15.40)
    )
  )
;; UPE 140
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "140"))
    (progn
      (setq taz_s_h 140.0)
      (setq taz_s_b 65.0)
      (setq taz_s_tw 5.0)
      (setq taz_s_tf 9.0)
      (setq taz_s_r1 12.0)
      (setq taz_s_ey 21.7)
      (setq taz_s_section_area 18.40)
    )
  )
;; UPE 160
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "160"))
    (progn
      (setq taz_s_h 160.0)
      (setq taz_s_b 70.0)
      (setq taz_s_tw 5.5)
      (setq taz_s_tf 9.5)
      (setq taz_s_r1 12.0)
      (setq taz_s_ey 22.7)
      (setq taz_s_section_area 21.70)
    )
  )
;; UPE 180
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "180"))
    (progn
      (setq taz_s_h 180.0)
      (setq taz_s_b 75.0)
      (setq taz_s_tw 5.5)
      (setq taz_s_tf 10.5)
      (setq taz_s_r1 12.0)
      (setq taz_s_ey 24.7)
      (setq taz_s_section_area 25.10)
    )
  )
;; UPE 200
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "200"))
    (progn
      (setq taz_s_h 200.0)
      (setq taz_s_b 80.0)
      (setq taz_s_tw 6.0)
      (setq taz_s_tf 11.0)
      (setq taz_s_r1 13.0)
      (setq taz_s_ey 25.6)
      (setq taz_s_section_area 29.00)
    )
  )
;; UPE 220
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "220"))
    (progn
      (setq taz_s_h 220.0)
      (setq taz_s_b 85.0)
      (setq taz_s_tw 6.5)
      (setq taz_s_tf 12.0)
      (setq taz_s_r1 13.0)
      (setq taz_s_ey 27.0)
      (setq taz_s_section_area 33.90)
    )
  )
;; UPE 240
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "240"))
    (progn
      (setq taz_s_h 240.0)
      (setq taz_s_b 90.0)
      (setq taz_s_tw 7.0)
      (setq taz_s_tf 12.5)
      (setq taz_s_r1 15.0)
      (setq taz_s_ey 27.9)
      (setq taz_s_section_area 38.50)
    )
  )
;; UPE 270
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "270"))
    (progn
      (setq taz_s_h 270.0)
      (setq taz_s_b 95.0)
      (setq taz_s_tw 7.5)
      (setq taz_s_tf 13.5)
      (setq taz_s_r1 15.0)
      (setq taz_s_ey 28.9)
      (setq taz_s_section_area 44.80)
    )
  )
;; UPE 300
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "300"))
    (progn
      (setq taz_s_h 300.0)
      (setq taz_s_b 100.0)
      (setq taz_s_tw 9.5)
      (setq taz_s_tf 15.0)
      (setq taz_s_r1 15.0)
      (setq taz_s_ey 28.9)
      (setq taz_s_section_area 56.60)
    )
  )
;; UPE 330
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "330"))
    (progn
      (setq taz_s_h 330.0)
      (setq taz_s_b 105.0)
      (setq taz_s_tw 11.0)
      (setq taz_s_tf 16.0)
      (setq taz_s_r1 18.0)
      (setq taz_s_ey 29.0)
      (setq taz_s_section_area 67.80)
    )
  )
;; UPE 360
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "360"))
    (progn
      (setq taz_s_h 360.0)
      (setq taz_s_b 110.0)
      (setq taz_s_tw 12.0)
      (setq taz_s_tf 17.0)
      (setq taz_s_r1 18.0)
      (setq taz_s_ey 29.7)
      (setq taz_s_section_area 77.90)
    )
  )
;; UPE 400
  (if (and (= taz_s_family "UPE")
           (= taz_s_type "400"))
    (progn
      (setq taz_s_h 400.0)
      (setq taz_s_b 115.0)
      (setq taz_s_tw 13.5)
      (setq taz_s_tf 18.0)
      (setq taz_s_r1 18.0)
      (setq taz_s_ey 29.8)
      (setq taz_s_section_area 91.90)
    )
  )  
)
