(defun taz_instalacja()
  (if (equal (vl-string-search ";C:\\TAZ\\STL" (vla-get-SupportPath (vla-get-files  (vla-get-preferences (vlax-get-Acad-object))))) nil)
    (vla-put-SupportPath (vla-get-files  (vla-get-preferences (vlax-get-Acad-object))) (strcat (vla-get-SupportPath (vla-get-files  (vla-get-preferences (vlax-get-Acad-object)))) ";C:\\TAZ\\STL"))
    (princ)
  )
  (if (equal (vl-string-search ";C:\\TAZ\\IMG" (vla-get-SupportPath (vla-get-files  (vla-get-preferences (vlax-get-Acad-object))))) nil)
    (vla-put-SupportPath (vla-get-files  (vla-get-preferences (vlax-get-Acad-object))) (strcat (vla-get-SupportPath (vla-get-files  (vla-get-preferences (vlax-get-Acad-object)))) ";C:\\TAZ\\IMG"))
    (princ)
  )
)
(taz_instalacja)
(vla-load (vla-get-menugroups (vlax-get-acad-object)) "C:\\TAZ\\taz.cuix")
(command "-TOOLBAR" "TAZ" "Float" "50,250" "1")
(princ "\n########## ZAINSTALOWANO TOOLBAR AZ ##########")
(princ)