(defun taz_start()
  (load "C:\\TAZ\\STL\\taz_s_annotation_scale.lsp")
  (load "C:\\TAZ\\STL\\taz_s_axes.dcl")
  (load "C:\\TAZ\\STL\\taz_s_axes.lsp")
  (load "C:\\TAZ\\STL\\taz_s_change_profile.lsp")
  (load "C:\\TAZ\\STL\\taz_s_create_beam.lsp")
  (load "C:\\TAZ\\STL\\taz_s_create_drawings_execution_design.dcl")
  (load "C:\\TAZ\\STL\\taz_s_create_drawings_execution_design.lsp")
  (load "C:\\TAZ\\STL\\taz_s_delete_beam.lsp")
  (load "C:\\TAZ\\STL\\taz_s_edit_attributes.dcl")
  (load "C:\\TAZ\\STL\\taz_s_edit_attributes.lsp")
  (load "C:\\TAZ\\STL\\taz_s_edit_beam_path_start.lsp")
  (load "C:\\TAZ\\STL\\taz_s_edit_beam_path_stop.lsp")
  (load "C:\\TAZ\\STL\\taz_s_edit_section_angle.lsp")
  (load "C:\\TAZ\\STL\\taz_s_edit_section_position.lsp")
  (load "C:\\TAZ\\STL\\taz_s_frame.dcl")
  (load "C:\\TAZ\\STL\\taz_s_frame.lsp")
  (load "C:\\TAZ\\STL\\taz_s_move_copy.dcl")
  (load "C:\\TAZ\\STL\\taz_s_move_copy.lsp")
  (load "C:\\TAZ\\STL\\taz_s_project_parameters.dcl")
  (load "C:\\TAZ\\STL\\taz_s_project_parameters.lsp")
  (load "C:\\TAZ\\STL\\taz_s_rebuild_data.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_cbeam_draw.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_cbeam_draw_parametres_upe.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_cbeam_draw_parametres_upn.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_hsbeam_draw.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_hsbeam_draw_parametres_rura_kwadratowa.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_hsbeam_draw_parametres_rura_okragla.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_hsbeam_draw_parametres_rura_prostokatna.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_ibeam_draw.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_ibeam_draw_parametres_hea.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_ibeam_draw_parametres_heb.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_ibeam_draw_parametres_ipe.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_ibeam_draw_parametres_ipn.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_lbeam_draw.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_lbeam_draw_parametres_katownik_nierownoramienny.lsp")
  (load "C:\\TAZ\\STL\\taz_s_section_lbeam_draw_parametres_katownik_rownoramienny.lsp")
  (load "C:\\TAZ\\STL\\taz_s_select_section.dcl")
  (load "C:\\TAZ\\STL\\taz_s_select_section.lsp")
  (load "C:\\TAZ\\STL\\taz_s_start.lsp")
  (princ)
)

(taz_start)
(princ "\n########## TOOLBAR AZ WLACZONY ##########")
(princ)
